import Link from "next/link";
import { DataUnavailable } from "@/components/system/DataUnavailable";
import { getActiveCompetition, getLiveEvents, getUpcomingEvents } from "@/lib/server/competition-repository";

export default async function ControlPage() {
  let data;
  try { data = await Promise.all([getActiveCompetition(), getLiveEvents(), getUpcomingEvents(5)]); }
  catch { return <DataUnavailable />; }
  const [competition, liveEvents, upcomingEvents] = data;
  return <main className="route-page"><header className="route-heading"><div><p className="overline">Control Room / Overview</p><h1>Matchday operations</h1><p>{competition?.name ?? "No active competition"} / What is live, next, and needs action.</p></div><Link className="secondary-button" href="/control/events">All events</Link></header><section className="route-section"><div className="section-heading"><div><span className="live-label">Live now</span><h2>{liveEvents.length ? `${liveEvents.length} event${liveEvents.length === 1 ? "" : "s"} in progress` : "No live events"}</h2></div></div>{liveEvents.map((event) => <Link className="event-row featured-event" href={`/control/events/${event.id}`} key={event.id}><span className="event-time"><span className="live-pulse" />{event.currentMinute}:00<span className="event-status">{event.status}</span></span><span className="event-match">{event.participants.map((entry) => <strong key={entry.participantId}>{entry.participant.name}</strong>)}</span><span className="event-meta">{event.venue.name}<br />{event.competition.name}</span><span className="row-action">Open event</span></Link>)}</section><section className="route-section"><div className="section-heading"><div><span className="overline">Next on the schedule</span><h2>Upcoming events</h2></div><span className="section-meta">{upcomingEvents.length} shown</span></div>{upcomingEvents.map((event) => <Link className="event-row" href={`/control/events/${event.id}`} key={event.id}><span className="event-time"><strong>{event.scheduledAt.toISOString().slice(11, 16)}</strong><span className="event-status">{event.status}</span></span><span className="event-match">{event.participants.map((entry) => <strong key={entry.participantId}>{entry.participant.name}</strong>)}</span><span className="event-meta">{event.venue.name}</span><span className="row-action">Details</span></Link>)}</section></main>;
}
