import Link from "next/link";
import { notFound } from "next/navigation";
import { DataUnavailable } from "@/components/system/DataUnavailable";
import { getCompetitionById } from "@/lib/server/competition-repository";

export default async function CompetitionPage({ params }: { params: Promise<{ competitionId: string }> }) {
  let competition;
  try { competition = await getCompetitionById((await params).competitionId); } catch { return <DataUnavailable title="Competition data unavailable" />; }
  if (!competition) notFound();
  const season = competition.seasons[0];
  return <main className="route-page"><header className="route-heading"><div><p className="overline">Control Room / Competitions</p><h1>{competition.name}</h1><p>{competition.region} / {competition.sport} / {season?.name}</p></div><Link className="secondary-button" href="/control/competitions">All competitions</Link></header><div className="filter-bar"><Link className="filter-active" href={`/control/competitions/${competition.id}`}>Overview</Link><Link href={`/control/events?competitionId=${competition.id}`}>Fixtures</Link></div><section className="overview-columns"><section className="overview-section"><div className="section-heading"><div><span className="overline">Registered participants</span><h2>{competition.participants.length} teams</h2></div></div>{competition.participants.map(({ participant }) => <div className="event-row" key={participant.id}><span className="event-time"><strong>{participant.code}</strong></span><span className="event-match"><strong>{participant.name}</strong></span><span className="event-meta">{participant.shortName}</span><span className="row-action">Active</span></div>)}</section><section className="overview-section"><div className="section-heading"><div><span className="overline">Standings</span><h2>{season?.standings.length ?? 0} teams ranked</h2></div></div><div className="standing-table"><div className="standing-head"><span>#</span><span>Team</span><span>P</span><span>W</span><span>D</span><span>L</span><span>GF</span><span>GA</span><span>GD</span><span>Pts</span></div>{season?.standings.map((standing, index) => <div className="standing-row" key={standing.id}><span>{index + 1}</span><strong>{standing.participant.shortName}</strong><span>{standing.played}</span><span>{standing.wins}</span><span>{standing.draws}</span><span>{standing.losses}</span><span>{standing.goalsFor}</span><span>{standing.goalsAgainst}</span><span>{standing.goalDifference}</span><strong>{standing.points}</strong></div>)}</div></section></section></main>;
}
