export function ControlRoomOverview({ onOpenEvent }: { onOpenEvent: () => void }) {
  return (
    <div className="view-wrap overview-view">
      <header className="view-heading"><div><p className="overline">Operations / Overview</p><h1>Matchday operations</h1><p className="view-description">Saturday, October 18, 2025. One event is currently live.</p></div><button className="secondary-button" onClick={onOpenEvent}>Open live event</button></header>
      <section className="overview-section live-section"><div className="section-heading"><div><span className="live-label">Live now</span><h2>One event requires your attention</h2></div><span className="section-meta">Updated 64:23</span></div><button className="event-row featured-event" onClick={onOpenEvent}><span className="event-time"><span className="live-pulse" />64:23<span className="event-status">LIVE</span></span><span className="event-match"><strong>Northbridge FC</strong><strong>1 - 0</strong><strong>Eastvale United</strong></span><span className="event-meta">Northeast Division<br />Riverside Stadium</span><span className="row-action">Open event</span></button></section>
      <div className="overview-columns"><section className="overview-section"><div className="section-heading"><div><span className="overline">Next on the schedule</span><h2>Upcoming events</h2></div><span className="section-meta">4 scheduled</span></div><div className="event-list"><EventRow time="10:30" home="Harbor City" away="Stonewall Athletic" note="Northeast Division" /><EventRow time="13:00" home="Westfield Rovers" away="AC Meridian" note="Northeast Division" /><EventRow time="15:30" home="Lakeside 04" away="Port Union" note="Southern Conference" /></div></section><section className="overview-section attention-section"><div className="section-heading"><div><span className="overline">Operator queue</span><h2>Needs action</h2></div><span className="section-meta">2 items</span></div><div className="queue-list"><button className="queue-row"><span className="queue-marker warning">!</span><span><strong>Lineups not confirmed</strong><small>Harbor City vs Stonewall</small></span><span className="row-action">Review</span></button><button className="queue-row"><span className="queue-marker">i</span><span><strong>Venue capacity update</strong><small>Westfield Rovers vs AC Meridian</small></span><span className="row-action">Review</span></button></div></section></div>
      <section className="activity-strip"><span className="overline">Recent operator activity</span><span><strong>12:48</strong> Jordan Mitchell published commentary on Northbridge FC vs Eastvale United</span><span><strong>12:41</strong> Goal recorded for Northbridge FC</span><button>View audit log</button></section>
    </div>
  );
}

function EventRow({ time, home, away, note }: { time: string; home: string; away: string; note: string }) { return <div className="event-row"><span className="event-time"><strong>{time}</strong><span className="event-status">UPCOMING</span></span><span className="event-match"><strong>{home}</strong><span>vs</span><strong>{away}</strong></span><span className="event-meta">{note}</span><span className="row-action">Details</span></div>; }

