import type { Dispatch, SetStateAction } from "react";
import type { EventStatus, Incident, IncidentType, Team } from "@/app/page";

type Props = { status: EventStatus; setStatus: Dispatch<SetStateAction<EventStatus>>; homeScore: number; awayScore: number; minute: number; setMinute: Dispatch<SetStateAction<number>>; incidents: Incident[]; addGoal: (team: Team) => void; addIncident: (type: IncidentType, label: string, team?: Team, detail?: string) => void; commentary: string[]; draft: string; setDraft: Dispatch<SetStateAction<string>>; publishCommentary: () => void };

export function EventControl({ status, setStatus, homeScore, awayScore, minute, setMinute, incidents, addGoal, addIncident, commentary, draft, setDraft, publishCommentary }: Props) {
  const isLive = status === "Live";
  return <div className="view-wrap event-view"><header className="event-context"><div><p className="overline">Live event / Northeast Division / Round 08</p><h1>Northbridge FC <span>vs</span> Eastvale United</h1><p className="event-location">Riverside Stadium, Northbridge <span>/</span> 12,840 public viewers</p></div><button className="secondary-button">Event details</button></header>
    <section className="match-banner"><div className="match-team home-team"><span className="team-badge">N</span><strong>Northbridge FC</strong><small>Home</small></div><div className="match-score"><div><strong>{homeScore}</strong><span>-</span><strong>{awayScore}</strong></div><span className={isLive ? "match-state live-state" : "match-state"}>{status.toUpperCase()}</span><time>{isLive ? `${String(minute).padStart(2, "0")}:23` : "--:--"}</time></div><div className="match-team away-team"><span className="team-badge away-badge">E</span><strong>Eastvale United</strong><small>Away</small></div></section>
    <div className="event-toolbar"><span className="toolbar-caption">Match control</span><button className="control-button primary-control" onClick={() => setStatus(isLive ? "Paused" : "Live")}>{isLive ? "Pause event" : "Resume event"}</button><button className="control-button" onClick={() => setStatus(status === "Finished" ? "Live" : "Finished")}>{status === "Finished" ? "Reopen event" : "End event"}</button><span className="toolbar-divider" /><label className="clock-control">Clock <input type="range" min="0" max="120" value={minute} onChange={(event) => setMinute(Number(event.target.value))} /><strong>{minute}:23</strong></label></div>
    <div className="event-workspace"><section className="feed-panel"><div className="panel-title-row"><div><span className="overline">Chronological event feed</span><h2>Match timeline</h2></div><span className="feed-source"><span className="state-light" /> Operator feed</span></div><div className="incident-feed">{incidents.slice().reverse().map((incident, index) => <IncidentRow incident={incident} key={`${incident.minute}-${index}`} />)}{isLive && <div className="feed-now"><span className="now-marker" /><span><strong>Live match in progress</strong><small>Waiting for the next event</small></span><time>now</time></div>}</div></section><aside className="publish-column"><section className="publish-panel"><div className="panel-title-row"><div><span className="overline">Fast entry</span><h2>Record incident</h2></div><span className="shortcut">F2</span></div><div className="quick-incident-grid"><button onClick={() => addGoal("Northbridge FC")}><strong>Goal</strong><small>Northbridge</small></button><button onClick={() => addGoal("Eastvale United")}><strong>Goal</strong><small>Eastvale</small></button><button onClick={() => addIncident("card", "Yellow card", "Northbridge FC", "Player booking")}><strong>Yellow card</strong><small>Northbridge</small></button><button onClick={() => addIncident("card", "Yellow card", "Eastvale United", "Player booking")}><strong>Yellow card</strong><small>Eastvale</small></button><button onClick={() => addIncident("substitution", "Substitution", undefined, "Player change")}><strong>Substitution</strong><small>Both teams</small></button><button onClick={() => addIncident("period", "Period ended", undefined, "Official time signal")}><strong>End period</strong><small>Match official</small></button></div><button className="text-control" onClick={() => addIncident("correction", "Correction logged", undefined, "Manual correction")}>Log correction</button></section><section className="publish-panel commentary-publish"><div className="panel-title-row"><div><span className="overline">Publishing</span><h2>Live commentary</h2></div><span className="publish-state">Ready to publish</span></div><div className="published-list">{commentary.slice(0, 2).map((item, index) => <div className="published-row" key={`${item}-${index}`}><time>{index === 0 ? `${minute}:23` : `${minute - 2}:08`}</time><p>{item}</p></div>)}</div><div className="composer"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Draft an update for Live Center" /><div><span>Draft only until published</span><button className="publish-button" onClick={publishCommentary}>Publish update</button></div></div></section></aside></div>
  </div>;
}

function IncidentRow({ incident }: { incident: Incident }) { return <div className="incident-row"><time>{String(incident.minute).padStart(2, "0")}:{incident.type === "goal" ? "12" : "00"}</time><span className={`incident-marker ${incident.type}`} /> <div><strong>{incident.label}</strong><span>{incident.team ?? "Match official"}</span><small>{incident.detail ?? "Event recorded in the operations feed"}</small></div><span className="incident-source">Operator</span></div>; }

