import Link from "next/link";
import { DataUnavailable } from "@/components/system/DataUnavailable";
import { getActiveCompetition, getFinishedEvents, getLiveEvents, getPublicNews, getUpcomingEvents } from "@/lib/server/competition-repository";

export default async function LivePage() {
  let data;
  try { data = await Promise.all([getActiveCompetition(), getLiveEvents(), getUpcomingEvents(4), getFinishedEvents(4), getPublicNews(3)]); }
  catch { return <DataUnavailable title="Live Center data unavailable" />; }
  const [competition, liveEvents, upcomingEvents, finishedEvents, news] = data;
  return <div className="public-view"><header className="public-header"><div className="public-wordmark">SPORTS LIVE OPS <span>/ LIVE CENTER</span></div><span className="public-competition">{competition?.name ?? "North American League"}</span><Link className="follow-button" href="/login">Control Room</Link></header><main className="public-main public-home"><header className="public-intro"><div><p className="overline">North American League / 2025 Fall Season</p><h1>Live competition, clearly reported.</h1><p className="event-location">Scores, events, and the latest from across the league.</p></div></header><section className="public-home-section"><div className="public-section-title"><h2>Live now</h2><span>{liveEvents.length} active</span></div>{liveEvents.length ? liveEvents.map((event) => <Link className="public-event-row" href={`/live/events/${event.id}`} key={event.id}><span className="public-live-status"><span className="state-light" />{event.currentMinute}:00</span><strong>{event.title}</strong><span>Follow match</span></Link>) : <p className="public-empty">No events are live right now.</p>}</section><div className="public-home-grid"><section className="public-home-section"><div className="public-section-title"><h2>Upcoming</h2><span>Next fixtures</span></div>{upcomingEvents.map((event) => <Link className="public-event-row" href={`/live/events/${event.id}`} key={event.id}><time>{event.scheduledAt.toISOString().slice(11, 16)}</time><strong>{event.title}</strong><span>{event.venue.name}</span></Link>)}</section><section className="public-home-section"><div className="public-section-title"><h2>Latest results</h2><span>Finished</span></div>{finishedEvents.map((event) => <div className="public-event-row" key={event.id}><time>{event.scheduledAt.toISOString().slice(0, 10)}</time><strong>{event.title}</strong><span>Final</span></div>)}</section></div><section className="public-home-section"><div className="public-section-title"><h2>Latest news</h2><span>From the league desk</span></div>{news.map((article) => <Link className="news-row" href={`/live/news/${article.id}`} key={article.id}><span className="overline">{article.publishedAt?.toISOString().slice(0, 10)}</span><strong>{article.title}</strong><p>{article.summary}</p></Link>)}</section></main></div>;
}
